version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging to AWS ECR
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=489148222993.dkr.ecr.us-east-1.amazonaws.com/bluegreenapp
  
  build:
    commands:
      - echo docker build started `date`
      - docker build -t $REPOSITORY_URI:latest .
  
  post_build:
    commands:
      - echo pushing image to ECR
      - docker push $REPOSITORY_URI:latest
      - writing the image defination file
      - printf '[{"name":"hello-world", "ImageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefination.json
  
  artifacts:
    files: imagedefination.json
